# -*- coding: utf-8 -*-
"""LMA SCRIPT REFACTOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONAmtqpPYpUtlVWp0xNczfvFggkupRRx
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""### Calculate Velocity Between Points

To calculate the velocity, we'll follow these steps:

1.  **Install the `haversine` library:** This library provides functions to calculate the distance between two points on a sphere (like Earth) given their latitude and longitude.
2.  **Calculate the Haversine distance:** For each point, we'll calculate the distance to the previous point using their `lat` and `lon` coordinates.
3.  **Calculate the time difference:** We'll determine the time elapsed between each consecutive pair of points using the `time` column.
4.  **Compute the velocity:** Velocity will be calculated as the distance divided by the time difference. The first point's velocity will be `NaN` as there is no preceding point.
5.  **Add a new `velocity` column:** The calculated velocities will be added as a new column to the `dflma` DataFrame.
"""

# Lembre-se de instalar o pacote no terminal com: pip install haversine
import sys

"""Now that the `velocity` column has been added to the `dflma` DataFrame, you can include it as another feature for clustering. This allows the clustering algorithm to consider the movement dynamics of the points in addition to their altitude and power."""

#lma_filename = '/content/drive/MyDrive/Mestrado LMA/DADOS LMA/LL_240720_234000_0600.dat/LL_240720_234000_0600.dat'

lma_filename = '/content/drive/MyDrive/Mestrado LMA/DADOS LMA/LL_20240720_235000_0600_map500m.nc'

hour = 23         #    <--- Insert whatever hour you want
minute = 45       #    <--- Insert whatever minute you want
sec = 00   #    <--- Insert whatever second you want

#   Translate to 'seconds from midnight'
sfm_target_time = (hour*3600) + (minute*60) + sec
#sfm_target_time = 85200.406334
sfm_target_time

dflma = pd.read_csv(
    lma_filename,
    sep=r'\s+',   # split by any whitespace, using raw string to fix SyntaxWarning
    header=None,             # no header row
    skiprows=55,             # skip first 55 rows
    names=['time','lat','lon','alt','chi','pw','hex']
)

display(dflma.describe())

# Operations moved from MRWnDXyxyTLz to ensure columns exist before filtering
# Convert the hexadecimal column to integer
dflma['hex_int'] = dflma['hex'].apply(lambda x: int(x, 16))

# Count how many '1' bits each hex number has
dflma['ns'] = dflma['hex_int'].apply(lambda x: bin(x).count('1'))
#display(dflma['time'])
#dflma['time'] = dflma['time'] - sfm_target_time # Subtract target time
#display(dflma['time'])
# Convert Altitude to km
dflma['alt'] = dflma['alt']/1000

#FILTERSSS

# Time Filter (removido para considerar todo o intervalo de tempo do arquivo inicialmente)
#dflma = dflma.query('time > 40')
#dflma = dflma.query('time < 41')

#Altitude filter
dflma = dflma.query('alt < 20')
dflma = dflma.query('alt > 0')

#Chi Filter
#dflma = dflma.query('chi < 0.4')

#Filter by power
#dflma = dflma.query('pw > 5')

#Number of stations Filter
#dflma = dflma.query('ns > 6')



from haversine import haversine_vector, Unit

# Prepare coordinates for haversine calculation
coords = list(zip(dflma['lat'], dflma['lon']))

# Calculate distances between consecutive points
# The first distance will be NaN as there's no previous point
distances = [0] + haversine_vector(coords[:-1], coords[1:], unit=Unit.KILOMETERS).tolist()

# Calculate time differences between consecutive points
# The first time difference will be NaN
time_diffs = dflma['time'].diff().fillna(0).tolist()

# Calculate velocity (distance / time difference)
# Handle cases where time_diff is zero to avoid division by zero
velocity = []
for i in range(len(distances)):
    if time_diffs[i] != 0:
        velocity.append(distances[i] / abs(time_diffs[i]))
    else:
        velocity.append(0) # or np.nan, depending on desired behavior for zero time diff

# Add the velocity column to the DataFrame
dflma['velocity'] = velocity

print("Velocity calculated and added to 'dflma' DataFrame.")
display(dflma[['time', 'lat', 'lon', 'velocity']].head())

dflma.describe()

"""adicionar o parâmetro de velocidade no cluster, o adonis passou qual algoritmo usar para calcular a velocidade de um ponto ao outro.

"""

from sklearn.preprocessing import StandardScaler

# Select the specified columns for clustering features, now including 'velocity'
features_for_clustering = dflma[['alt', 'pw', 'velocity']]

# Instantiate StandardScaler
scaler = StandardScaler()

# Fit the scaler to the features and transform the data
scaled_features = scaler.fit_transform(features_for_clustering)

print("Selected features for clustering (including velocity):")
print(features_for_clustering.head())
print("\nScaled features (first 5 rows):")
print(scaled_features[:5])
print(f"Shape of scaled_features: {scaled_features.shape}")

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

lblsize = 16 # Define lblsize as it was used in previous plotting cells
ticksize = 15 # Define ticksize for consistency, though not used in this specific plot

wcss = []
k_range = range(1, 16)  # Test k from 1 to 15

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto') # n_init='auto' to suppress warning
    kmeans.fit(scaled_features)
    wcss.append(kmeans.inertia_)

# Plot the Elbow Method results
plt.figure(figsize=(10, 6))
plt.plot(k_range, wcss, marker='o', linestyle='-')
plt.xlabel('Número de Clusters (k)', size=lblsize)
plt.ylabel('WCSS (Soma dos Quadrados Intra-Cluster)', size=lblsize)
plt.title('Método do Cotovelo para K-Means', size=lblsize + 2)
plt.xticks(k_range) # Ensure all k values are shown on x-axis
plt.grid(True)
plt.show()

print("WCSS values calculated and Elbow Method plot displayed.")

from sklearn.cluster import KMeans

# Based on the elbow plot, let's choose k=4 as the optimal number of clusters.
k_optimal = 4

# Instantiate KMeans with the optimal number of clusters
kmeans_model = KMeans(n_clusters=k_optimal, random_state=42, n_init='auto')

# Fit the KMeans model to the scaled features
kmeans_model.fit(scaled_features)

# Get the cluster labels
cluster_labels = kmeans_model.labels_

# Add the cluster labels as a new column to the original dflma DataFrame
dflma['cluster'] = cluster_labels

print(f"K-Means clustering applied with k={k_optimal} clusters.")
print("First 5 rows of dflma with new 'cluster' column:")
print(dflma[['time', 'lat', 'lon', 'alt', 'pw', 'cluster']].head())

import matplotlib.pyplot as plt

fig6, ax6 = plt.subplots(figsize=(10, 7))
scatter = ax6.scatter(dflma['lon'], dflma['lat'], c=dflma['cluster'], cmap='viridis', s=10)
ax6.set_xlabel("Longitude (degrees)", size=lblsize)
ax6.set_ylabel("Latitude (degrees)", size=lblsize)
ax6.set_title("Distribuição Espacial dos Clusters (Latitude vs. Longitude)", size=lblsize + 2)
ax6.tick_params(labelsize=ticksize)
cbar = fig6.colorbar(scatter, ax=ax6)
cbar.set_label('Cluster ID', size=lblsize)
plt.tight_layout()
plt.show()

fig7, ax7 = plt.subplots(figsize=(10, 7))
scatter = ax7.scatter(dflma['time'], dflma['alt'], c=dflma['cluster'], cmap='viridis', s=10)
ax7.set_xlabel("Time (s)", size=lblsize)
ax7.set_ylabel("Altitude (km)", size=lblsize)
ax7.set_title("Distribuição Temporal e Altitudinal dos Clusters", size=lblsize + 2)
ax7.tick_params(labelsize=ticksize)
cbar = fig7.colorbar(scatter, ax=ax7)
cbar.set_label('Cluster ID', size=lblsize)
plt.tight_layout()
plt.show()

cluster_stats = dflma.groupby('cluster')[['alt', 'pw', 'velocity']].agg(['mean', 'min', 'max'])

print("Estatísticas descritivas para cada cluster:")
display(cluster_stats)

import matplotlib.pyplot as plt

unique_clusters = dflma['cluster'].unique()
num_clusters = len(unique_clusters)

fig_alt_hist, axs_alt_hist = plt.subplots(num_clusters, 1, figsize=(10, 5 * num_clusters), sharex=True)

# Ensure axs_alt_hist is always an array, even for a single subplot
if num_clusters == 1:
    axs_alt_hist = [axs_alt_hist]

for i, cluster_id in enumerate(sorted(unique_clusters)):
    cluster_data = dflma[dflma['cluster'] == cluster_id]
    axs_alt_hist[i].hist(cluster_data['alt'], bins=30, alpha=0.7, color=plt.cm.viridis(cluster_id / (num_clusters - 1)), edgecolor='black')
    axs_alt_hist[i].set_title(f'Altitude Distribution - Cluster {cluster_id}', size=lblsize + 2)
    axs_alt_hist[i].set_ylabel('Counts', size=lblsize)
    axs_alt_hist[i].tick_params(labelsize=ticksize)
    axs_alt_hist[i].grid(True)

axs_alt_hist[-1].set_xlabel('Altitude (km)', size=lblsize)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

unique_clusters = dflma['cluster'].unique()
num_clusters = len(unique_clusters)

fig_pw_hist, axs_pw_hist = plt.subplots(num_clusters, 1, figsize=(10, 5 * num_clusters), sharex=True)

# Ensure axs_pw_hist is always an array, even for a single subplot
if num_clusters == 1:
    axs_pw_hist = [axs_pw_hist]

for i, cluster_id in enumerate(sorted(unique_clusters)):
    cluster_data = dflma[dflma['cluster'] == cluster_id]
    axs_pw_hist[i].hist(cluster_data['pw'], bins=30, alpha=0.7, color=plt.cm.jet(cluster_id / (num_clusters - 1)), edgecolor='black')
    axs_pw_hist[i].set_title(f'Power Distribution - Cluster {cluster_id}', size=lblsize + 2)
    axs_pw_hist[i].set_ylabel('Counts', size=lblsize)
    axs_pw_hist[i].tick_params(labelsize=ticksize)
    axs_pw_hist[i].grid(True)

axs_pw_hist[-1].set_xlabel('Power (dB)', size=lblsize)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

fig_3d = plt.figure(figsize=(12, 10))
ax_3d = fig_3d.add_subplot(111, projection='3d')

scatter_3d = ax_3d.scatter(dflma['lon'], dflma['lat'], dflma['alt'], c=dflma['cluster'], cmap='viridis', s=10)

ax_3d.set_xlabel('Longitude (degrees)', size=lblsize)
ax_3d.set_ylabel('Latitude (degrees)', size=lblsize)
ax_3d.set_zlabel('Altitude (km)', size=lblsize)
ax_3d.set_title('3D Spatial Distribution of Clusters (Lon x Lat x Alt)', size=lblsize + 2)

cbar_3d = fig_3d.colorbar(scatter_3d, ax=ax_3d, pad=0.1)
cbar_3d.set_label('Cluster ID', size=lblsize)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

fig_alt_pw, ax_alt_pw = plt.subplots(figsize=(10, 7))
scatter_alt_pw = ax_alt_pw.scatter(dflma['pw'], dflma['alt'], c=dflma['cluster'], cmap='viridis', s=10)

ax_alt_pw.set_xlabel('Power (dB)', size=lblsize)
ax_alt_pw.set_ylabel('Altitude (km)', size=lblsize)
ax_alt_pw.set_title('Altitude vs. Power (Color by Cluster)', size=lblsize + 2)
ax_alt_pw.tick_params(labelsize=ticksize)
ax_alt_pw.grid(True)

cbar_alt_pw = fig_alt_pw.colorbar(scatter_alt_pw, ax=ax_alt_pw)
cbar_alt_pw.set_label('Cluster ID', size=lblsize)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

unique_clusters = dflma['cluster'].unique()
num_clusters = len(unique_clusters)

fig_vel_hist, axs_vel_hist = plt.subplots(num_clusters, 1, figsize=(10, 5 * num_clusters), sharex=True)

# Ensure axs_vel_hist is always an array, even for a single subplot
if num_clusters == 1:
    axs_vel_hist = [axs_vel_hist]

for i, cluster_id in enumerate(sorted(unique_clusters)):
    cluster_data = dflma[dflma['cluster'] == cluster_id]
    axs_vel_hist[i].hist(cluster_data['velocity'], bins=30, alpha=0.7, color=plt.cm.cividis(cluster_id / (num_clusters - 1)), edgecolor='black')
    axs_vel_hist[i].set_title(f'Velocity Distribution - Cluster {cluster_id}', size=lblsize + 2)
    axs_vel_hist[i].set_ylabel('Counts', size=lblsize)
    axs_vel_hist[i].tick_params(labelsize=ticksize)
    axs_vel_hist[i].grid(True)

axs_vel_hist[-1].set_xlabel('Velocity (km/s)', size=lblsize)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.hist(dflma['velocity'], bins=50, alpha=0.7, color='skyblue', edgecolor='black')
plt.title('Histograma da Velocidade', size=lblsize + 2)
plt.xlabel('Velocity (km/s)', size=lblsize)
plt.ylabel('Frequência', size=lblsize)
plt.tick_params(labelsize=ticksize)
plt.grid(True)
plt.show()